// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gvcaipqaspgguzgncupa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd2Y2FpcHFhc3BnZ3V6Z25jdXBhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgwOTg0OTksImV4cCI6MjA3MzY3NDQ5OX0.bMw7V91tU81MTilLH7E94Hju6kRfcDrL5ehIXZ5MQAE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});